spring:
  profiles:
    active: default
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heytogether?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: heytogether
    password: 12heytogether
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR
